#ifndef MINIGAME_SRC_ASSET_STB_VORBIS_HPP_INCLUDED
#define MINIGAME_SRC_ASSET_STB_VORBIS_HPP_INCLUDED

#define STB_VORBIS_HEADER_ONLY

#include "../third_party/stb/stb_vorbis.c"

#endif // MINIGAME_SRC_ASSET_STB_VORBIS_HPP_INCLUDED
